# Generated by Django 4.0.4 on 2022-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='null', max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
