# Generated by Django 4.0.4 on 2022-04-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_site_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='site_admin',
        ),
    ]
